spring:
  application:
    name: spring-security-example
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5435/spring_boot_security
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8200